version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
  
  directus:
    image: directus/directus:11.5.1
    container_name: directus_app
    ports:
      - "8055:8055"
    depends_on:
      - database
    environment:
      EMAIL_VERIFY_SETUP: "true"
      EMAIL_TRANSPORT: "smtp"
      EMAIL_SMTP_HOST: "mailhog"
      EMAIL_SMTP_PORT: "1025"
      KEY: "mysecretkey"
      SECRET: "mysecretkey"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin123"
      DB_CLIENT: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      PUBLIC_URL: "http://localhost:8055"
      CORS_ENABLED: "true"
      CORS_ORIGIN: "true"
      CORS_ALLOWED_HEADERS: "Content-Type, Authorization"
      CORS_ALLOWED_METHODS: "GET, POST, PATCH, DELETE, OPTIONS"
      CORS_EXPOSED_HEADERS: "Content-Length, Content-Range"
      CORS_CREDENTIALS: "true"
      USER_INVITE_URL_ALLOW_LIST: "http://localhost:5173/invitehandler"
      SESSION_COOKIE_NAME: "directus_session_token"
      SESSION_COOKIE_SECURE : "false"
      REFRESH_TOKEN_COOKIE_NAME: "directus_refresh_token"
      ACCESS_TOKEN_TTL: "900"                   
      REFRESH_TOKEN_TTL: "604800"                
      REFRESH_TOKEN_COOKIE: "true"                 
      REFRESH_TOKEN_COOKIE_SECURE: "false"        
      REFRESH_TOKEN_COOKIE_SAME_SITE: "lax"   

      
    volumes:
      - directus_uploads:/directus/uploads
    restart: unless-stopped


  database:
    image: postgres:15
    container_name: directus_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "directus"
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  directus_uploads:
  pgdata:
